### ISSUE TITLE
Input/target dimensions with cudnn.SpatialCrossEntropyCriterion

### ISSUE THREAD

**Issue by rracinskij** [fedor-chervinskii/segnet-torch#2]
Hi,
thank you for your impressive work!
Could you please explain the required dimensionality of outputs and targets to use it with `cudnn.SpatialCrossEntropyCriterion()` as in your Yandex repo? Segnet model input is `[batchSize, numChannels, H, W] `and the output is `[batchSize, numClasses, H, W]`. But `cudnn.SpatialCrossEntropyCriterion()` requires the target to be of size `[batchSize, H, W]`. So it looks like that the model outputs `numClasses` separate masks for each class while the criterion expects a single mask with all the classes within it.
I can't get through this issue while reproducing the model with a toy example.

**Comment by fedor-chervinskii** [comment]
Hi @rracinskij !
As you can find in the [source code](https://github.com/soumith/cudnn.torch/blob/master/SpatialCrossEntropyCriterion.lua#L25) of `cudnn.SpatialCrossEntropyCriterion()`, this criterion takes 1-channel target, so you put in each pixel its corresponding class index. Still your output will have size `[batchSize, numClasses, H, W]`.

Also this repo is a bit deprecated, I recommend use Yandex one. Although it requires more adjustment for use, it already allows you to train in batches, while this code that you comment on originally allows only training in batches of size 1.

**Comment by rracinskij** [comment]
Hi @fedor-chervinskii ,
thanks a lot for your explanation and advice!
